//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acredores
    {
        public Acredores()
        {
            this.Deducciones = new HashSet<Deducciones>();
        }
    
        public int IdAcredor { get; set; }
        public string Acredor { get; set; }
        public string ACH { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<Deducciones> Deducciones { get; set; }
    }
}
