//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaCobros
    {
        public AgendaCobros()
        {
            this.ResultadosGestion = new HashSet<ResultadosGestion>();
        }
    
        public int IdAgenda { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> DiasAtraso { get; set; }
        public Nullable<decimal> MontoAdeudado { get; set; }
        public Nullable<decimal> CicloCorrriente { get; set; }
        public Nullable<decimal> Ciclo60 { get; set; }
        public Nullable<decimal> Ciclo90 { get; set; }
        public Nullable<decimal> Ciclo120 { get; set; }
        public Nullable<decimal> CicloMas120 { get; set; }
        public Nullable<int> IdTipoCompromiso { get; set; }
    
        public virtual TiposCompromiso TiposCompromiso { get; set; }
        public virtual ICollection<ResultadosGestion> ResultadosGestion { get; set; }
        public virtual Cobradores Cobradores { get; set; }
    }
}
