//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenaje
    {
        public Almacenaje()
        {
            this.RA = new HashSet<RA>();
            this.VentasMoviles = new HashSet<VentasMoviles>();
        }
    
        public int IdAlmacen { get; set; }
        public Nullable<int> IdTipoAlmacen { get; set; }
        public string Almacen { get; set; }
        public string Descripción { get; set; }
        public Nullable<System.DateTime> FechaCreación { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual TiposAlmacen TiposAlmacen { get; set; }
        public virtual ICollection<RA> RA { get; set; }
        public virtual ICollection<VentasMoviles> VentasMoviles { get; set; }
    }
}
