//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public Asientos()
        {
            this.DetalleAsientos = new HashSet<DetalleAsientos>();
        }
    
        public int IdAsiento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTransaccion { get; set; }
        public Nullable<int> IdRegistroBanco { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdUser { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdOrigen { get; set; }
        public string Importante { get; set; }
        public Nullable<int> IdTipoAsiento { get; set; }
    
        public virtual ICollection<DetalleAsientos> DetalleAsientos { get; set; }
    }
}
