//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public Asientos()
        {
            this.DetalleAsientos = new HashSet<DetalleAsientos>();
        }
    
        public int IdAsiento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdTransaccion { get; set; }
        public Nullable<int> IdRegistroBanco { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Comentario { get; set; }
        public int IdUser { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ICollection<DetalleAsientos> DetalleAsientos { get; set; }
    }
}
