//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        public Bancos()
        {
            this.RegistrosBanco = new HashSet<RegistrosBanco>();
        }
    
        public int IdBanco { get; set; }
        public string Banco { get; set; }
        public string NumeroCuenta { get; set; }
    
        public virtual ICollection<RegistrosBanco> RegistrosBanco { get; set; }
    }
}
