//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Productos = new HashSet<Productos>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int IdCategoria { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> ITBMS { get; set; }
        public Nullable<decimal> IngresoSubsidio { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
