//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Productos = new HashSet<Productos>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int IdCategoria { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> ITBMS { get; set; }
        public Nullable<decimal> IngresoSubsidio { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
    }
}
