//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CicloAlmacenaje
    {
        public int IdPeridoSilo { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<System.DateTime> LLenadoDesde { get; set; }
        public Nullable<System.DateTime> LLenadoHasta { get; set; }
        public Nullable<System.DateTime> VaciadoDesde { get; set; }
        public Nullable<System.DateTime> VaciadoHasta { get; set; }
        public Nullable<decimal> PorcentajeEnteroE { get; set; }
        public Nullable<decimal> PorcentajeQuebradoE { get; set; }
        public Nullable<decimal> RendimientoEstimado { get; set; }
        public Nullable<decimal> TotalBruto { get; set; }
        public Nullable<decimal> TotalNeto { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> TotalPilado { get; set; }
        public Nullable<decimal> PorcentajeEnteroF { get; set; }
        public Nullable<decimal> PorcentajeQuebradoF { get; set; }
        public Nullable<decimal> RendimientoFinal { get; set; }
    }
}
