//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaboradores
    {
        public Colaboradores()
        {
            this.HorasTrabajadas = new HashSet<HorasTrabajadas>();
            this.Deducciones = new HashSet<Deducciones>();
            this.IngresosDeduccionesHoras = new HashSet<IngresosDeduccionesHoras>();
            this.RegistroOtrosDeducciones = new HashSet<RegistroOtrosDeducciones>();
            this.RegistroVacaciones = new HashSet<RegistroVacaciones>();
            this.RegistroLiquidaciones = new HashSet<RegistroLiquidaciones>();
            this.PlanillaColaborador = new HashSet<PlanillaColaborador>();
        }
    
        public int IdColaborador { get; set; }
        public string Colaborador { get; set; }
        public Nullable<int> IdEstadoColaborador { get; set; }
        public Nullable<int> IdContratoColaborador { get; set; }
        public Nullable<decimal> SalarioQuincenal { get; set; }
        public Nullable<decimal> CTORepresentacion { get; set; }
        public string EstadoCivil { get; set; }
        public string IdentificacionPersonal { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> IdEntidadFinanciera { get; set; }
        public Nullable<System.TimeSpan> HoraEntrada { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdPosicion { get; set; }
        public Nullable<decimal> RataPorHora { get; set; }
        public Nullable<decimal> Bonificaciones { get; set; }
        public string SeguroSocial { get; set; }
        public string Sangre { get; set; }
        public Nullable<int> IdRenta { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Dependientes { get; set; }
        public Nullable<bool> ExentoRenta { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual ContratosColaborador ContratosColaborador { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual EntedidadesFinanciera EntedidadesFinanciera { get; set; }
        public virtual EstadosColaborador EstadosColaborador { get; set; }
        public virtual Posiciones Posiciones { get; set; }
        public virtual Rentas Rentas { get; set; }
        public virtual Colaboradores Colaboradores1 { get; set; }
        public virtual Colaboradores Colaboradores2 { get; set; }
        public virtual ICollection<HorasTrabajadas> HorasTrabajadas { get; set; }
        public virtual ICollection<Deducciones> Deducciones { get; set; }
        public virtual ICollection<IngresosDeduccionesHoras> IngresosDeduccionesHoras { get; set; }
        public virtual ICollection<RegistroOtrosDeducciones> RegistroOtrosDeducciones { get; set; }
        public virtual ICollection<RegistroVacaciones> RegistroVacaciones { get; set; }
        public virtual ICollection<RegistroLiquidaciones> RegistroLiquidaciones { get; set; }
        public virtual ICollection<PlanillaColaborador> PlanillaColaborador { get; set; }
    }
}
