//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slEntities : DbContext
    {
        public slEntities()
            : base("name=slEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<ClasesCliente> ClasesCliente { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<TiposCliente> TiposCliente { get; set; }
        public virtual DbSet<DetallesPerfil> DetallesPerfil { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<VAsientos> VAsientos { get; set; }
        public virtual DbSet<FormasPago> FormasPago { get; set; }
        public virtual DbSet<FPagoUilizada> FPagoUilizada { get; set; }
        public virtual DbSet<Transacciones> Transacciones { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<RegistrosBanco> RegistrosBanco { get; set; }
        public virtual DbSet<Cotizaciones> Cotizaciones { get; set; }
        public virtual DbSet<DetalleCotizacion> DetalleCotizacion { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<PrecioProducto> PrecioProducto { get; set; }
        public virtual DbSet<Precios> Precios { get; set; }
        public virtual DbSet<VPrecioLista> VPrecioLista { get; set; }
        public virtual DbSet<DetallesTransaccione> DetallesTransaccione { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
    }
}
