//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public Cotizaciones()
        {
            this.DetalleCotizacion = new HashSet<DetalleCotizacion>();
        }
    
        public int IdCotizacion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cotizacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<DetalleCotizacion> DetalleCotizacion { get; set; }
    }
}
