//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public Cotizaciones()
        {
            this.DetalleCotizacion = new HashSet<DetalleCotizacion>();
        }
    
        public int IdCotizacion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cotizacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<DetalleCotizacion> DetalleCotizacion { get; set; }
    }
}
