//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deducciones
    {
        public Deducciones()
        {
            this.IngresosDeducciones = new HashSet<IngresosDeducciones>();
        }
    
        public int IdDeduccion { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public string Deduccion { get; set; }
        public string TipoDeduccion { get; set; }
        public Nullable<int> IdAcredor { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> ArregloRecurrente { get; set; }
    
        public virtual Acredores Acredores { get; set; }
        public virtual Colaboradores Colaboradores { get; set; }
        public virtual ICollection<IngresosDeducciones> IngresosDeducciones { get; set; }
    }
}
