//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deducciones
    {
        public Deducciones()
        {
            this.IngresosDeducciones = new HashSet<IngresosDeducciones>();
        }
    
        public int IdDeduccion { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public string Deduccion { get; set; }
        public string TipoDeduccion { get; set; }
        public Nullable<int> IdAcredor { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> ArregloRecurrente { get; set; }
    
        public virtual Acredores Acredores { get; set; }
        public virtual Colaboradores Colaboradores { get; set; }
        public virtual ICollection<IngresosDeducciones> IngresosDeducciones { get; set; }
    }
}
