//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public Descuentos()
        {
            this.DetallesDescuento = new HashSet<DetallesDescuento>();
        }
    
        public int IdDescuento { get; set; }
        public Nullable<int> IdAcredor { get; set; }
        public string Descuento { get; set; }
        public string NumeroPrestamo { get; set; }
        public Nullable<bool> DescuentoDiciembre { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual ICollection<DetallesDescuento> DetallesDescuento { get; set; }
    }
}
