//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        public Descuentos()
        {
            this.DetallesDescuento = new HashSet<DetallesDescuento>();
        }
    
        public int IdDescuento { get; set; }
        public Nullable<int> IdAcredor { get; set; }
        public string Descuento { get; set; }
        public string NumeroPrestamo { get; set; }
        public Nullable<bool> DescuentoDiciembre { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual ICollection<DetallesDescuento> DetallesDescuento { get; set; }
    }
}
