//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAsientos
    {
        public int IdDetalleAsiento { get; set; }
        public Nullable<int> IdAsiento { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> idProvedor { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdMaestroCuenta { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual MaestroCuentas MaestroCuentas { get; set; }
    }
}
