//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesDescuento
    {
        public int IdDetalleDescuento { get; set; }
        public Nullable<int> IdDescuento { get; set; }
        public Nullable<int> FechaDescuento { get; set; }
        public string CorrespondeA { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Descuentos Descuentos { get; set; }
    }
}
