//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesFacturaItem
    {
        public int IdDetalleFacturaItem { get; set; }
        public Nullable<int> IdDetalleFactura { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> ITBMS { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<bool> ActualizaInventario { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
    
        public virtual DetallesFactura DetallesFactura { get; set; }
    }
}
