//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentasMovil
    {
        public int IdDetalleVentaMovil { get; set; }
        public Nullable<int> IdVentaMovil { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual VentasMoviles VentasMoviles { get; set; }
    }
}
