//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int IdDetalleCotizacion { get; set; }
        public Nullable<int> IdCotizacion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Detalle { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<decimal> Itbm { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Cotizaciones Cotizaciones { get; set; }
    }
}
