//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesTransaccione
    {
        public int IdDetalleTransaccion { get; set; }
        public int IdTransaccion { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> ITBM { get; set; }
        public Nullable<decimal> Propina { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IdPrecioProducto { get; set; }
        public Nullable<decimal> IngresoSubsidio { get; set; }
    
        public virtual Servicios Servicios { get; set; }
        public virtual Transacciones Transacciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
