//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPerfil
    {
        public int IdDetallePerfil { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> Deshabilitar { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
