//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesFactura
    {
        public DetallesFactura()
        {
            this.DetallesFacturaItem = new HashSet<DetallesFacturaItem>();
        }
    
        public int IdDetalleFactura { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> ITBMS { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> RItbms { get; set; }
        public Nullable<int> IdProducto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual MaestroCuentas MaestroCuentas { get; set; }
        public virtual ICollection<DetallesFacturaItem> DetallesFacturaItem { get; set; }
    }
}
