//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPerfil
    {
        public int IdDetallePerfil { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> Deshabilitar { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
