//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacion
    {
        public int IdDetalleCotizacion { get; set; }
        public Nullable<int> IdCotizacion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Detalle { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<decimal> Itbm { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Cotizaciones Cotizaciones { get; set; }
    }
}
