//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public Empresas()
        {
            this.RegistrosBanco = new HashSet<RegistrosBanco>();
            this.Transacciones = new HashSet<Transacciones>();
            this.Servicios = new HashSet<Servicios>();
            this.Productos = new HashSet<Productos>();
        }
    
        public string Empresa { get; set; }
        public string Ruc { get; set; }
        public string Dv { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int IdEmpresa { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdItbms { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdIngresos { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public Nullable<int> IdEfectivoBanco { get; set; }
    
        public virtual ICollection<RegistrosBanco> RegistrosBanco { get; set; }
        public virtual ICollection<Transacciones> Transacciones { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
