//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosColaborador
    {
        public EstadosColaborador()
        {
            this.Colaboradores = new HashSet<Colaboradores>();
        }
    
        public int IdEstadoColaborador { get; set; }
        public string EstadoColaborador { get; set; }
    
        public virtual ICollection<Colaboradores> Colaboradores { get; set; }
    }
}
