//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factores
    {
        public Factores()
        {
            this.HorasTrabajadas = new HashSet<HorasTrabajadas>();
            this.IngresosDeduccionesHoras = new HashSet<IngresosDeduccionesHoras>();
        }
    
        public int IdFactor { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string DescripcionFactor { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<int> IdTipoFactor { get; set; }
        public Nullable<bool> RestaSaldo { get; set; }
        public string TipoDia { get; set; }
    
        public virtual TiposFactor TiposFactor { get; set; }
        public virtual ICollection<HorasTrabajadas> HorasTrabajadas { get; set; }
        public virtual ICollection<IngresosDeduccionesHoras> IngresosDeduccionesHoras { get; set; }
    }
}
