//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factores
    {
        public Factores()
        {
            this.HorasTrabajadas = new HashSet<HorasTrabajadas>();
            this.IngresosDeduccionesHoras = new HashSet<IngresosDeduccionesHoras>();
        }
    
        public int IdFactor { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string DescripcionFactor { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<int> IdTipoFactor { get; set; }
        public Nullable<bool> RestaSaldo { get; set; }
        public string TipoDia { get; set; }
    
        public virtual TiposFactor TiposFactor { get; set; }
        public virtual ICollection<HorasTrabajadas> HorasTrabajadas { get; set; }
        public virtual ICollection<IngresosDeduccionesHoras> IngresosDeduccionesHoras { get; set; }
    }
}
