//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.DetallesFactura = new HashSet<DetallesFactura>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> DiasPlazo { get; set; }
        public string ModoPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> ITBM { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> IdProvedor { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual ICollection<DetallesFactura> DetallesFactura { get; set; }
    }
}
