//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPago
    {
        public FormasPago()
        {
            this.FPagoUilizada = new HashSet<FPagoUilizada>();
        }
    
        public int IdFormaPago { get; set; }
        public string FormaPago { get; set; }
        public Nullable<bool> habilitar { get; set; }
    
        public virtual ICollection<FPagoUilizada> FPagoUilizada { get; set; }
    }
}
