//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPagoUilizada
    {
        public int IdFPagoUtilizada { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdTransaccion { get; set; }
    
        public virtual FormasPago FormasPago { get; set; }
        public virtual Transacciones Transacciones { get; set; }
    }
}
