//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPagoUilizada
    {
        public int IdFPagoUtilizada { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdTransaccion { get; set; }
    
        public virtual FormasPago FormasPago { get; set; }
        public virtual Transacciones Transacciones { get; set; }
    }
}
