//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestiones
    {
        public Gestiones()
        {
            this.ResultadosGestion = new HashSet<ResultadosGestion>();
        }
    
        public int IdGestion { get; set; }
        public string Gestion { get; set; }
        public Nullable<int> IdTipoGestion { get; set; }
    
        public virtual TiposGestion TiposGestion { get; set; }
        public virtual ICollection<ResultadosGestion> ResultadosGestion { get; set; }
    }
}
