//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasTrabajadas
    {
        public int IdHoraTrabjada { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdFactor { get; set; }
        public Nullable<decimal> HoraTrabajada { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public Nullable<bool> Procesado { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
        public virtual Factores Factores { get; set; }
    }
}
