//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public int IdInventario { get; set; }
        public Nullable<int> IdPeridoSilo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdTipoMovimiento { get; set; }
        public Nullable<int> IdRa { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PorcentajeDescuentoSilo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<decimal> PorcentajeEntero { get; set; }
        public Nullable<decimal> PorcentajeQuebrado { get; set; }
    
        public virtual TiposMovimiento TiposMovimiento { get; set; }
    }
}
