//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroCuentas
    {
        public MaestroCuentas()
        {
            this.DetalleAsientos = new HashSet<DetalleAsientos>();
            this.DetallesFactura = new HashSet<DetallesFactura>();
        }
    
        public int IdMaestroCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Text { get; set; }
        public int ParentID { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<bool> Habilitar { get; set; }
        public Nullable<int> SumaResta { get; set; }
        public string Nivel0 { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
    
        public virtual ICollection<DetalleAsientos> DetalleAsientos { get; set; }
        public virtual ICollection<DetallesFactura> DetallesFactura { get; set; }
    }
}
