//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroCuentas
    {
        public MaestroCuentas()
        {
            this.DetalleAsientos = new HashSet<DetalleAsientos>();
            this.DetallesFactura = new HashSet<DetallesFactura>();
        }
    
        public int IdMaestroCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Text { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<bool> Habilitar { get; set; }
        public Nullable<int> SumaResta { get; set; }
        public string Nivel0 { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
        public string CuentaContable { get; set; }
        public string Nivel4 { get; set; }
        public Nullable<bool> EsBanco { get; set; }
        public Nullable<bool> EsCompra { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<bool> EsProveedor { get; set; }
        public Nullable<bool> EsCliente { get; set; }
        public Nullable<int> UltimoCheque { get; set; }
    
        public virtual ICollection<DetalleAsientos> DetalleAsientos { get; set; }
        public virtual ICollection<DetallesFactura> DetallesFactura { get; set; }
    }
}
