//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.DetallesPerfil = new HashSet<DetallesPerfil>();
        }
    
        public int IdPerfil { get; set; }
        public string Perfil1 { get; set; }
    
        public virtual ICollection<DetallesPerfil> DetallesPerfil { get; set; }
    }
}
