//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.DetallesPerfil = new HashSet<DetallesPerfil>();
        }
    
        public int IdPerfil { get; set; }
        public string Perfil1 { get; set; }
    
        public virtual ICollection<DetallesPerfil> DetallesPerfil { get; set; }
    }
}
