//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaColaborador
    {
        public int Id { get; set; }
        public int IdColaborador { get; set; }
        public int IdEmpresa { get; set; }
        public int IdUser { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public int Año { get; set; }
        public int Mes { get; set; }
        public int Quincena { get; set; }
        public Nullable<decimal> RataPorHora { get; set; }
        public Nullable<decimal> SalarioQuincenal { get; set; }
        public Nullable<decimal> TotalHoras { get; set; }
        public Nullable<decimal> SalarioBruto { get; set; }
        public Nullable<decimal> OtrasDeducciones { get; set; }
        public Nullable<decimal> CXCRecurrentes { get; set; }
        public Nullable<decimal> CXC { get; set; }
        public Nullable<decimal> SeguroSocial { get; set; }
        public Nullable<decimal> SeguroEducativo { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public Nullable<decimal> SeguroSocialPatronal { get; set; }
        public Nullable<decimal> SeguroEducativoPatronal { get; set; }
        public Nullable<decimal> Decimo { get; set; }
        public Nullable<decimal> Vacacciones { get; set; }
        public Nullable<decimal> SalarioNeto { get; set; }
        public Nullable<decimal> indemnizacion { get; set; }
        public Nullable<decimal> Antiguedad { get; set; }
        public Nullable<decimal> Recerva { get; set; }
        public Nullable<decimal> Riesgo { get; set; }
        public Nullable<int> PeriodDecimo { get; set; }
        public Nullable<decimal> SeguroSocialDecimo { get; set; }
        public Nullable<decimal> SeguroSocialDecimoPatrono { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
    }
}
