//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioProducto
    {
        public int IdPrecioProducto { get; set; }
        public Nullable<int> IdPrecio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Precios Precios { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
