//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios
    {
        public Precios()
        {
            this.Clientes = new HashSet<Clientes>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
        }
    
        public int IdPrecio { get; set; }
        public string Precio { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
    }
}
