//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios
    {
        public Precios()
        {
            this.Clientes = new HashSet<Clientes>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
        }
    
        public int IdPrecio { get; set; }
        public string Precio { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
    }
}
