//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioProducto
    {
        public int IdPrecioProducto { get; set; }
        public Nullable<int> IdPrecio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Precios Precios { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
