//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetallesTransaccione = new HashSet<DetallesTransaccione>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
        }
    
        public int IdProducto { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Productos1 { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<int> PuntoReorden { get; set; }
    
        public virtual ICollection<DetallesTransaccione> DetallesTransaccione { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
        public virtual Categorias Categorias { get; set; }
    }
}
