//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetallesTransaccione = new HashSet<DetallesTransaccione>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
        }
    
        public int IdProducto { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Productos1 { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<int> PuntoReorden { get; set; }
    
        public virtual ICollection<DetallesTransaccione> DetallesTransaccione { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
        public virtual Categorias Categorias { get; set; }
    }
}
