//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productores
    {
        public int IdProductor { get; set; }
        public Nullable<int> IdProcedencia { get; set; }
        public string Productor { get; set; }
        public string Cedula { get; set; }
    }
}
