//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class provedores
    {
        public int idProvedor { get; set; }
        public string Proveedor { get; set; }
        public string Contacto { get; set; }
        public string ContactoTitulo { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string HomePage { get; set; }
        public string Ruc { get; set; }
        public Nullable<bool> EsProductor { get; set; }
    }
}
