//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class provedores
    {
        public int idProvedor { get; set; }
        public string Proveedor { get; set; }
        public string Contacto { get; set; }
        public string ContactoTitulo { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string HomePage { get; set; }
        public string Ruc { get; set; }
        public Nullable<bool> EsProductor { get; set; }
        public Nullable<int> IdProcencia { get; set; }
    }
}
