//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroOtrosDeducciones
    {
        public int IdOtraDeduccion { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public string Deduccion { get; set; }
        public string TipoDeduccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
    }
}
