//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroLiquidaciones
    {
        public int IdRegistroLiquidacion { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<decimal> Antiguedad { get; set; }
        public Nullable<decimal> Indemnizacion { get; set; }
        public Nullable<decimal> NoReintegro { get; set; }
        public Nullable<decimal> DecimoProporcional { get; set; }
        public Nullable<decimal> VacacionesProporcionales { get; set; }
        public Nullable<decimal> Social { get; set; }
        public Nullable<decimal> Educativo { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public Nullable<decimal> Liquidacion { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
    }
}
