//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosBanco
    {
        public int IdRegistroBanco { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string NumeroCheque { get; set; }
        public Nullable<System.DateTime> FechaCheque { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> IdDebito { get; set; }
        public Nullable<int> IdCredito { get; set; }
        public Nullable<int> idProvedor { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdAsiento { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
