//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosBanco
    {
        public int IdRegistroBanco { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string NumeroCheque { get; set; }
        public Nullable<System.DateTime> FechaCheque { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> IdDebito { get; set; }
        public Nullable<int> IdCredito { get; set; }
        public Nullable<int> idProvedor { get; set; }
        public Nullable<int> IdColaborador { get; set; }
        public Nullable<int> IdAsiento { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
