//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentas
    {
        public Rentas()
        {
            this.Colaboradores = new HashSet<Colaboradores>();
        }
    
        public int IdRenta { get; set; }
        public string Renta { get; set; }
    
        public virtual ICollection<Colaboradores> Colaboradores { get; set; }
    }
}
