//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadosGestion
    {
        public ResultadosGestion()
        {
            this.HistorialCliente = new HashSet<HistorialCliente>();
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int IdResultadoGestion { get; set; }
        public Nullable<int> IdAgenda { get; set; }
        public Nullable<System.DateTime> FechaGestion { get; set; }
        public Nullable<int> IdGestion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<decimal> MontoArreglo { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<int> EstadoPromesa { get; set; }
        public Nullable<System.DateTime> FechaReprogramacion { get; set; }
        public Nullable<int> IdCobrador { get; set; }
        public Nullable<int> EstadoReprogramacion { get; set; }
    
        public virtual AgendaCobros AgendaCobros { get; set; }
        public virtual ICollection<HistorialCliente> HistorialCliente { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ResultadosGestion ResultadosGestion1 { get; set; }
        public virtual ResultadosGestion ResultadosGestion2 { get; set; }
        public virtual Gestiones Gestiones { get; set; }
    }
}
