//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public Servicios()
        {
            this.PrecioProducto = new HashSet<PrecioProducto>();
            this.DetallesTransaccione = new HashSet<DetallesTransaccione>();
        }
    
        public int IdServicio { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Servicios1 { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
        public virtual ICollection<DetallesTransaccione> DetallesTransaccione { get; set; }
        public virtual Categorias Categorias { get; set; }
    }
}
