//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slContabilidad : DbContext
    {
        public slContabilidad()
            : base("name=slContabilidad")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<VPagosProveedor> VPagosProveedor { get; set; }
        public virtual DbSet<Asientos> Asientos { get; set; }
        public virtual DbSet<DetalleAsientos> DetalleAsientos { get; set; }
        public virtual DbSet<MaestroCuentas> MaestroCuentas { get; set; }
        public virtual DbSet<VMayorAsientos> VMayorAsientos { get; set; }
        public virtual DbSet<DetallesFacturaItem> DetallesFacturaItem { get; set; }
        public virtual DbSet<provedores> provedores { get; set; }
        public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Almacenes> Almacenes { get; set; }
    }
}
