//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slContabilidad : DbContext
    {
        public slContabilidad()
            : base("name=slContabilidad")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<VPagosProveedor> VPagosProveedor { get; set; }
        public virtual DbSet<Asientos> Asientos { get; set; }
        public virtual DbSet<DetalleAsientos> DetalleAsientos { get; set; }
        public virtual DbSet<MaestroCuentas> MaestroCuentas { get; set; }
        public virtual DbSet<VMayorAsientos> VMayorAsientos { get; set; }
        public virtual DbSet<DetallesFacturaItem> DetallesFacturaItem { get; set; }
        public virtual DbSet<provedores> provedores { get; set; }
        public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Almacenes> Almacenes { get; set; }
        public virtual DbSet<VCuentasMaestras> VCuentasMaestras { get; set; }
        public virtual DbSet<VCuentasPrimarias> VCuentasPrimarias { get; set; }
        public virtual DbSet<SesionesAplicacion> SesionesAplicacion { get; set; }
    }
}
