//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slGestiones : DbContext
    {
        public slGestiones()
            : base("name=slGestiones")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgendaCobros> AgendaCobros { get; set; }
        public virtual DbSet<Cobradores> Cobradores { get; set; }
        public virtual DbSet<Gestiones> Gestiones { get; set; }
        public virtual DbSet<HistorialCliente> HistorialCliente { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<ResultadosGestion> ResultadosGestion { get; set; }
        public virtual DbSet<TiposCompromiso> TiposCompromiso { get; set; }
        public virtual DbSet<TiposGestion> TiposGestion { get; set; }
    }
}
