//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposGestion
    {
        public TiposGestion()
        {
            this.Gestiones = new HashSet<Gestiones>();
        }
    
        public int IdTipoGestion { get; set; }
        public string TipoGestion { get; set; }
    
        public virtual ICollection<Gestiones> Gestiones { get; set; }
    }
}
