//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposAlmacen
    {
        public TiposAlmacen()
        {
            this.Almacenaje = new HashSet<Almacenaje>();
        }
    
        public int IdTipoAlmacen { get; set; }
        public string TipoAlmacen { get; set; }
    
        public virtual ICollection<Almacenaje> Almacenaje { get; set; }
    }
}
