//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposMovimiento
    {
        public TiposMovimiento()
        {
            this.Kardex = new HashSet<Kardex>();
        }
    
        public int IdTipoMovimiento { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<bool> Resta { get; set; }
    
        public virtual ICollection<Kardex> Kardex { get; set; }
    }
}
