//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposCliente
    {
        public TiposCliente()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int IdTipoCliente { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
