//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposFactor
    {
        public TiposFactor()
        {
            this.Factores = new HashSet<Factores>();
        }
    
        public int IdTipoFactor { get; set; }
        public string Factor { get; set; }
    
        public virtual ICollection<Factores> Factores { get; set; }
    }
}
