//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public Transacciones()
        {
            this.FPagoUilizada = new HashSet<FPagoUilizada>();
            this.DetallesTransaccione = new HashSet<DetallesTransaccione>();
        }
    
        public int IdTransaccion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoImpuestos { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string CuponFiscal { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual ICollection<FPagoUilizada> FPagoUilizada { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ICollection<DetallesTransaccione> DetallesTransaccione { get; set; }
    }
}
