//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.RegistrosBanco = new HashSet<RegistrosBanco>();
        }
    
        public int IdUser { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fechaCumpleaño { get; set; }
        public Nullable<int> CodRol { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string nombreCompleto { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> IdPerfil { get; set; }
    
        public virtual ICollection<RegistrosBanco> RegistrosBanco { get; set; }
    }
}
