//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAsientos
    {
        public int IdAsiento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Comentario { get; set; }
        public int IdDetalleAsiento { get; set; }
        public Nullable<int> DetalleAsientos_IdAsiento { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public int IdCuentaContable { get; set; }
        public string Cuenta { get; set; }
        public Nullable<long> IdA { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Id { get; set; }
        public string Nivel2 { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string CedulaRuc { get; set; }
        public string Banco { get; set; }
        public string Proveedor { get; set; }
        public string Ruc { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> idProvedor { get; set; }
        public string usuario { get; set; }
        public string CuentaContable { get; set; }
        public string Mayor { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> IdOrigen { get; set; }
    }
}
