//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasMoviles
    {
        public VentasMoviles()
        {
            this.DetalleVentasMovil = new HashSet<DetalleVentasMovil>();
        }
    
        public int IdVentaMovil { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string NumeroRecibo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Almacenaje Almacenaje { get; set; }
        public virtual ICollection<DetalleVentasMovil> DetalleVentasMovil { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
