//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMayorAsientos
    {
        public int IdDetalleAsiento { get; set; }
        public string Cuenta { get; set; }
        public int IdCuentaContable { get; set; }
        public int N { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
        public string Nivel4 { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Empresa { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdAsiento { get; set; }
    }
}
