//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMayorAsientos
    {
        public int IdDetalleAsiento { get; set; }
        public string Cuenta { get; set; }
        public int IdCuentaContable { get; set; }
        public int N { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
        public string Nivel4 { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Empresa { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdAsiento { get; set; }
    }
}
