//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPagosProveedor
    {
        public int IdFactura { get; set; }
        public Nullable<int> IdProvedor { get; set; }
        public string Glosa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<decimal> MontoAdeudado { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<int> DiasTranscurridos { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<decimal> ArregloPago { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public decimal Corriente { get; set; }
        public decimal Morosidad60 { get; set; }
        public decimal Morosidad90 { get; set; }
        public decimal Morosidad120 { get; set; }
        public decimal MorosidadMas120 { get; set; }
        public string Cliente { get; set; }
        public string Empresa { get; set; }
        public byte[] img { get; set; }
        public Nullable<decimal> MontoProducto { get; set; }
        public string ProductoServicio { get; set; }
    }
}
