//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPlanilla
    {
        public int IdColaborador { get; set; }
        public string Colaborador { get; set; }
        public string Sexo { get; set; }
        public Nullable<decimal> SalarioDevengado { get; set; }
        public Nullable<decimal> SeguroEducativo { get; set; }
        public Nullable<decimal> SeguroSocial { get; set; }
        public decimal Renta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public decimal OtrasDeducciones { get; set; }
        public string Mes { get; set; }
        public decimal Extras { get; set; }
        public decimal Amonestacion { get; set; }
        public decimal CXC { get; set; }
        public string DesdeHasta { get; set; }
        public string Departamento { get; set; }
        public Nullable<decimal> RataPorHora { get; set; }
        public decimal Domingos { get; set; }
        public decimal Feriados { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Posicion { get; set; }
        public string Empresa { get; set; }
        public string Ruc { get; set; }
        public string Dv { get; set; }
    }
}
