//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPrecioLista
    {
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string Productos { get; set; }
        public Nullable<int> PuntoReorden { get; set; }
        public Nullable<decimal> ITBMS { get; set; }
        public int IdPrecio { get; set; }
        public int IdPrecioProducto { get; set; }
    }
}
