//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siro
{
    using System;
    using System.Collections.Generic;
    
    public partial class VValoresAlmacenaje
    {
        public long ID { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<System.DateTime> FechaLLenadoDesde { get; set; }
        public Nullable<System.DateTime> FechaLLenadoHasta { get; set; }
        public Nullable<decimal> TotalBruto { get; set; }
        public Nullable<decimal> PorcentajeHumedadE { get; set; }
        public Nullable<decimal> PorcentajeImpurezasE { get; set; }
        public Nullable<decimal> PorcentajeEnteroE { get; set; }
        public Nullable<decimal> PorcentajeQuebradoE { get; set; }
        public Nullable<decimal> RendimientoE { get; set; }
        public Nullable<decimal> TotalNeto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<System.DateTime> FechaPiladoDesde { get; set; }
        public Nullable<System.DateTime> FechaPiladoHasta { get; set; }
        public Nullable<decimal> TotalPilado { get; set; }
        public Nullable<decimal> AjusteTotal { get; set; }
        public Nullable<decimal> PorcentajeEnteroF { get; set; }
        public Nullable<decimal> PorcentajeQuebradoF { get; set; }
        public Nullable<decimal> RendimientoF { get; set; }
        public Nullable<decimal> InventarioFinal { get; set; }
        public Nullable<decimal> Seco { get; set; }
        public string Almacen { get; set; }
        public string TipoArroz { get; set; }
    }
}
